sistana: migrate from local lab
ArcletProject/Alconna pull request #91
Opened 2024-09-20 10:11 UTC by GreyElaina

2024-09-20 16:50 UTC, GreyElaina commented
敬请见证：https://wakatime.com/@9b922d20-ae54-4b73-81de-c31145268b46

2024-09-21 19:52 UTC, RF-Tar-Railt reviewed
model这边加点comment或者docstring

2024-09-21 19:52 UTC, RF-Tar-Railt commented on src/arclet/alconna/sistana/analyzer.py
```python
    def loopflow(self, snapshot: AnalyzeSnapshot[T], buffer: Buffer[T]) -> LoopflowDescription:
        while True:
            traverse = snapshot.traverses[-1]
            context = traverse.subcommand
            mix = traverse.mix

            if snapshot.determined and self.complete_on_determined and mix.satisfied:
                return LoopflowDescription.completed

            pointer_type, pointer_val = traverse.ref.data[-1]

            try:
                token = buffer.next(traverse.subcommand.separators)
            except OutOfData:
                if mix.satisfied:
                    mix.complete_all()

                    # 在 option context 里面，因为 satisfied 了，所以可以直接返回 completed。
                    # 并且还得确保 option 也被记录于 activated_options 里面。
                    if pointer_type == "option":
                        mix.tracks[pointer_val].complete()
                        option_traverse = traverse.option_traverses[-1]
                        option_traverse.completed = True
                        traverse.ref = traverse.ref.parent

                        if context.options[pointer_val].allow_duplicate:
                            mix.pop_track(pointer_val)

                    snapshot.determine(traverse.ref)
                    return LoopflowDescription.completed

                # 这里如果没有 satisfied，如果是 option 的 track，则需要 reset
                # 从 Buffer 吃掉的东西？我才不还。
                if pointer_type == "option":
                    mix.reset(pointer_val)

                return LoopflowDescription.unsatisfied

            if pointer_type == "prefix":
                if not isinstance(token.val, str):
                    return LoopflowDescription.header_expect_str

                if context.prefixes is not None:
                    prefix = context.prefixes.get_closest_prefix(buffer.runes[0])  # type: ignore
                    if prefix == "":
                        return LoopflowDescription.prefix_mismatch

                    token.apply()
                    buffer.pushleft(token.val[len(prefix) :])

                traverse.ref = traverse.ref.parent.header()  # 直接进 header.
            elif pointer_type == "header":
                if not isinstance(token.val, str):
                    return LoopflowDescription.header_expect_str

                token.apply()

                if token.val == context.header:
                    pass  # do nothing
                elif context.compact_header and token.val.startswith(context.header):
                    # ahead 似乎并不能很好的处理这种情况：这里目的不是为了分「完全已知」的段落，而是分一半 —— 去掉并留置。
                    # 再次重申，ahead 里的所有段落全都是「已经分好」了的。
                    # 在 perfix 和 header 中，我们需要对 buffer 的第一段进行直接替换，而 ahead 倾向于 **已经** 分好段的情况。
                    # ~~而除了 compact subcommand / option 外，对于 header 和 prefix，可以选择直接操作 runes[0]。~~

                    v = token.val[len(context.header) :]
                    if v:
                        buffer.runes.insert(0, v)
                else:
                    return LoopflowDescription.header_mismatch

                traverse.ref = traverse.ref.parent
            elif isinstance(token.val, str):
                if pointer_type == "subcommand":
                    if token.val in context.subcommands:
                        subcommand = context.subcommands[token.val]

                        if mix.satisfied or not subcommand.satisfy_previous:
                            token.apply()
                            mix.complete_all()

                            # context hard switch
                            snapshot.traverses.append(
                                SubcommandTraverse(
                                    subcommand,
                                    token.val,
                                    traverse.ref.subcommand(subcommand.header),
                                    subcommand.preset.new_mix(),
                                )
                            )
                            continue
                        elif not subcommand.soft_keyword:
                            return LoopflowDescription.unsatisfied_switch_subcommand
                        # else: soft keycmd，直接进 mainline
                    elif token.val in context.options:
                        option = context.options[token.val]

                        # 之前的版本中如果 track 没有 satisfied，就会继续进入 track forward 流程。
                        # 这里有个问题，如果 Fragments 里有个 variadic，那么就会一直进入 forward 流程 —— 这就不太对了，所以我删掉了。
                        if not option.soft_keyword or mix.satisfied:
                            if context.preset.tracks[option.keyword]:
                                # 仅当需要解析 fragments 时进行状态流转。
                                traverse.ref = traverse.ref.option(token.val)

                            if not option.allow_duplicate and option.keyword in traverse.option_traverses:
                                return LoopflowDescription.option_duplicated

                            traverse.option_traverses.append(
                                OptionTraverse(
                                    trigger=token.val,
                                    is_compact=False,
                                    completed=not context.preset.tracks[option.keyword],
                                    option=option,
                                    track=mix.tracks[option.keyword],
                                )
                            )

                            token.apply()  # 在最后才 apply，因为上面会根据 duplicate 的情况判定 panic，不能一开始就吃掉。
                            continue
                        # else: What?
                    # else: What?
                else:  # pointer_type == "option"
                    option_traverse = traverse.option_traverses[-1]

                    if token.val in context.subcommands:
                        # 当且仅当 option 已经 satisfied 时才能让状态流转进 subcommand。
                        # subcommand.satisfy_previous 处理起来比较复杂，这里先 reject。

                        # 对于 OptionPattern.allow_duplicate。
                        subcommand = context.subcommands[token.val]
                        option = context.options[pointer_val]
                        track = mix.tracks[option.keyword]
                        
                        if track.satisfied:
                            track.complete()
                            traverse.ref = traverse.ref.parent
                            option_traverse.completed = True

                            if option.allow_duplicate:
                                mix.pop_track(option.keyword)

                            if mix.satisfied:
                                token.apply()
                                mix.complete_all()

                                # context hard switch
                                snapshot.traverses.append(
                                    SubcommandTraverse(
                                        subcommand,
                                        token.val,
                                        traverse.ref.subcommand(token.val),
                                        subcommand.preset.new_mix(),
                                    )
                                )
                                continue
                            elif not subcommand.soft_keyword:
                                return LoopflowDescription.unsatisfied_switch_subcommand
                        elif not subcommand.soft_keyword:
                            mix.reset(option.keyword)
                            return LoopflowDescription.switch_unsatisfied_option
                        # else: soft keycmd，直接进 mainline ?

                    elif token.val in context.options:
                        option = context.options[token.val]
                        track = mix.tracks[option.keyword]

                        if not track.satisfied:
                            if not option.soft_keyword:
                                mix.reset(option.keyword)
              [...]

2024-09-21 19:52 UTC, RF-Tar-Railt commented on src/arclet/alconna/sistana/utils/misc.py
> +        var.reset(token)
tarina 里有个的
https://github.com/ArcletProject/Tarina/blob/c71cae3a8a5e4751decfa48aab19939d0091f97f/src/tarina/context.py#L11

2024-09-21 19:52 UTC, RF-Tar-Railt commented on src/arclet/alconna/sistana/fragment.py
> +            self.capture = RegexCapture(pat.alias)
if pat.mode in (MatchMode.REGEX_MATCH, MatchMode.REGEX_CONVERT):
    self.capture = RegexCapture(pat.regex_pattern)
else:
    self.capture = RegexCapture(pat.alias)  # ?

2024-09-21 19:58 UTC, RF-Tar-Railt commented on src/arclet/alconna/sistana/analyzer.py
以及我感觉你都不用写一个class Analyser了，直接把loopflow 拿出来（

2024-09-22 08:39 UTC, GreyElaina commented on src/arclet/alconna/sistana/analyzer.py
你的 else branch question 的答案全是进 track  process 或者是进下一个循环。

2024-09-22 09:02 UTC, GreyElaina commented on src/arclet/alconna/sistana/utils/misc.py
> +        var.reset(token)
这个没用 —— 并且 BCC 也有一个和你 Tarina 这个完全一致的版本。

并且目前就我个人观点，我认为写成这个 `cvar` 反而是更简洁许多的。

只是这个并没有在 sistana 中用到，后续我会把这个删掉。

2024-09-22 10:13 UTC, GreyElaina reviewed
> 以及按目前代码我感觉你都不用写一个class Analyser了，直接把loopflow 拿出来（ 

关于这个我有异议：我计划为 Analyzer 提供一些 option 以控制其行为，虽然现 Flywheel 在处理 descriptor 上仍有欠缺，在 Analyzer 上设置 Flywheel Anycast 或许是不错的想法。

2024-09-25 18:40 UTC, GreyElaina commented
别急，转 Ready for Review / Merge 前我先看看能修多少个测试

2024-09-26 10:52 UTC, GreyElaina commented
将进行一次大的重构，添加新的功能与更健全的状态流转设计

2024-10-08 02:55 UTC, RF-Tar-Railt commented on src/arclet/alconna/model.py
>          self.name = name
删了吧）

2024-10-08 02:55 UTC, RF-Tar-Railt commented on src/arclet/alconna/sistana/err.py
> +class ReceivePanic(ParsePanic): ...
如果可以的话，写到alconna.exception里

2024-10-08 03:28 UTC, GreyElaina commented on src/arclet/alconna/model.py
>          self.name = name
对 arclet.alconna.[^(sistana)(_stargazing)] 的修改都是参考用的……

2024-10-10 03:42 UTC, RF-Tar-Railt requested changes

2024-10-10 03:42 UTC, RF-Tar-Railt commented on pyproject.toml
>  pythonPlatform = "All"
这里改成 3.9

2024-10-10 03:42 UTC, RF-Tar-Railt commented on src/arclet/alconna/sistana/fragment.py
> +            self.transformer = _transform
https://github.com/ArcletProject/Alconna/commit/3e1a49e038f1fc0c9c1bc86b2114f313b1fbb07e#diff-aad2c1776c92e0bc33c357affa6830f52b94c1c25da92a2b18be2ebbf217cbe8L6-R98

2024-10-10 07:38 UTC, RF-Tar-Railt approved these changes

2024-10-12 07:54 UTC, merged